### PR TITLE
Added un-prefixed CSS properties for Ffx, IE

### PR DESCRIPTION
**Pull request by stopsatgreen**
Tested in Firefox, works as expected. Not tested in IE.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR, @stopsatgreen. Before this PR can be merged, could you sign the CLA? :) See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by addyosmani** [comment]
ping.

**Comment by stopsatgreen** [comment]
Sorry, will do this over the weekend.

**Comment by stopsatgreen** [comment]
https://github.com/Polymer/polymer.github.io/pull/13

**Comment by ebidel** [comment]
Thanks for signing the CLA!

**Comment by addyosmani** [comment]
Our apologies for this PR slipping through the cracks. With the new rewrite under way, older experimental elements like this are only periodically being reviewed. Landing your change now. Thank you :)

**Pull request merged**
