### PR TITLE
Use 'attached' for deprecated 'enteredView' and 'detached' etc...

### PR DESCRIPTION
**Pull request by ghost**
Just working through some example code and I couldn't get the 'enteredView' function to fire so found that it had been replaced by 'attached' in my version of Polymer 0.5.1.  Similarly for 'removed' to 'detached'

core-component-page#0.5.1 bower_components/core-component-page
├── polymer#0.5.1
└── webcomponentsjs#0.5.1

(Attributed : https://www.dartlang.org/docs/tutorials/polymer-intro/)

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for your PR! Before this can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by ghost** [comment]
I have signed the Google CLA at https://cla.developers.google.com/clas/new?kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE - is this the right one?  

I can't seem to find where to change the label to cla:yes - I assume it is that I don't have access rights on this repo to do so.  Should I submit another PR?

Many thanks

**Comment by addyosmani** [comment]
Don't worry about it. This has been manually verified. Sorry for our CLA bot causing you issues the first time you tried to get this through.

**Comment by addyosmani** [comment]
Later note: this element is in all likelihood deprecated. I'll continue to monitor for changes in case anyone is still using this through the designer.

**Pull request merged**
